# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicemade', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=10)),
                ('input', models.CharField(blank=True, max_length=200)),
                ('choice1', models.CharField(blank=True, max_length=200)),
                ('choice2', models.CharField(blank=True, max_length=200)),
                ('choice3', models.CharField(blank=True, max_length=200)),
                ('choice4', models.CharField(blank=True, max_length=200)),
                ('choice5', models.CharField(blank=True, max_length=200)),
                ('choice6', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Set'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
