# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170904_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Userprofile'),
        ),
    ]
