# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170904_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastanswered',
            new_name='toanswer',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Userprofile'),
        ),
    ]
